input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    RingbitCar.running_time(RingbitCar.Direction_run.forward, 1.9)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.left, 90)
    RingbitCar.running_time(RingbitCar.Direction_run.forward, 1.6)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.right, 95)
    RingbitCar.running_time(RingbitCar.Direction_run.forward, 3.8)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.left, 220)
    RingbitCar.running_time(RingbitCar.Direction_run.forward, 5)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.left, 85)
    RingbitCar.forward()
})
RingbitCar.init_wheel(AnalogPin.P1, AnalogPin.P2)
